### ISSUE TITLE
Can't run on custom dataset

### ISSUE THREAD

**Issue by beombeompow** [diegothomas/TetraTSDF#2]
Hello,

I could make 3D mesh .ply file use this code with single RGB image.
It was amazing.

However I want to train own custom dataset.
I tried it with ./coarsehuman/README.md, but there is no comment of running genTSDF.py on custom images, meshes.
I need data/.ply, smplparams/.pkl, /joints/*.ply of custom meshes.
I guess I should use smpl code, smplify code to get them.
Could you update some guides for that?

Thanks.

**Comment by diegothomas** [comment]
Hi,

Thank you for your interest in the project.

To train on your own dataset you need to prepare the ground truth from your dataset.
What you need is:
1. 3D poses in the SMPL format (you can use software like VIBE for example: https://github.com/mkocabas/VIBE)
2. For each image and the corresponding 3D scan, fit the SMPL model to the scan to get the skinning weights. 
3. With the skinning weights transform the scan in the star-shape pose.
4. for each summit of each tetrahedra of the coarse human model compute the signed distance function (sdf) to the 3D scan (in the star shape pose).
5. Save this sdf data in binary format. (look at the code in ./coarsehuman/gendata_Articulated/ for example)
6. Also crop all your images (./coarsehuman/gendata_Articulated/cropimg.py).

I hope this helps you!
Best

**Comment by beombeompow** [comment]
Thanks for fast reply.

Did you mean using VIBE that I can get 
[./smplfitresults_articulated/data/*.ply] files, and 
[./smplfitresults_articulated/joints/*.ply] files for custom data?
And using SMPL that I can get
[./smplfitresults_articulated/smplparams/*.pkl] files for custom data?

**Comment by diegothomas** [comment]
Hello,

No sorry, with VIBE you can only obtain the SMPL parameters (shape and pose) -> smplparams/*.pkl
For the .ply you need to skin your 3D scans to the star shape pose (by using the smpl parameters for example).
I assume that you have the raw 3D scans (maybe in .ply format) of the captured persons?

**Comment by beombeompow** [comment]
Thanks for kind response.
I got it.

Have a Good Day!
